- hosts: localhost
  connection: local
  tasks:

  # sync ntp befor apt-get
  # - name: Copy systemd-timesyncd
  #   copy:
  #     src: {{ ansible_facts['env']['HOME'] }}/dotfiles/ansible/files/etc/systemd/timesyncd.conf
  #     dest: /etc/systemd/timesyncd.conf
  #     backup: yes
  # - name: restart systemd-timesyncd
  #   systemd:
  #     state: restarted
  #     daemon_reload: yes
  #     name: systemd-timesyncd

  # Copy apt settings
  #- name: Copy /etc/apt/sources.list
  #  copy:
  #    src: {{ ansible_facts['env']['HOME'] }}/dotfiles/ansible/files/etc/apt/sources.list
  #    dest: /etc/apt/sources.list
  #    backup: yes

  - apt: name={{ item.name }} state=present
    become: yes
    loop:
      # cui for japanease
      - { name: fbterm }
      - { name: uim-fep }
      - { name: uim-mozc }
      # command
      - { name: curl }
      - { name: git }
      - { name: nodejs }
      - { name: tmux }
      - { name: ripgrep }
      - { name: fzf }
        #- { name: rsync }
        #- { name: gawk }
        #- { name: busybox }
        #- { name: bindfs }
      # gui
      - { name: xinit }
      - { name: i3 }
      - { name: rxvt-unicode }
      - { name: x11-xserver-utils }

  - file:
      src: "{{ ansible_facts['env']['HOME'] }}/dotfiles/{{ item.src }}"
      dest: "{{ ansible_facts['env']['HOME'] }}/{{ item.dest }}"
      state: link
    loop:
      - { src: '.Xresources', dest: '.Xresources' }
      - { src: '.uim', dest: '.uim' }

  # Copy settings
  #- name: Copy keyboard
  #  copy:
  #    src: {{ ansible_facts['env']['HOME'] }}/dotfiles/ansible/files/etc/default/keyboard
  #    dest: /etc/default/keyboard
  #    backup: yes
  #- name: Copy dhcpcd.conf
  #  copy:
  #    src: {{ ansible_facts['env']['HOME'] }}/dotfiles/ansible/files/etc/dhcpcd.conf
  #    dest: /etc/dhcpcd.conf
  #    backup: yes
  #- name: Copy wpa_supplicant.conf (Wi-Fi)
  #  copy:
  #    src: {{ ansible_facts['env']['HOME'] }}/dotfiles/ansible/files/etc/wpa_supplicant/wpa_supplicant.conf
  #    dest: /etc/wpa_supplicant/wpa_supplicant.conf
  #    backup: yes

