- hosts: localhost
  connection: local
  tasks:

  # sync ntp befor apt-get
  # - name: Copy systemd-timesyncd
  #   copy:
  #     src: {{ ansible_facts['env']['HOME'] }}/dotfiles/ansible/files/etc/systemd/timesyncd.conf
  #     dest: /etc/systemd/timesyncd.conf
  #     backup: yes
  # - name: restart systemd-timesyncd
  #   systemd:
  #     state: restarted
  #     daemon_reload: yes
  #     name: systemd-timesyncd

  # Copy apt settings
  #- name: Copy /etc/apt/sources.list
  #  copy:
  #    src: {{ ansible_facts['env']['HOME'] }}/dotfiles/ansible/files/etc/apt/sources.list
  #    dest: /etc/apt/sources.list
  #    backup: yes

  - apt: name={{ item.name }} state=present
    become: yes
    loop:
      # cui for japanease
      - { name: fbterm }
      - { name: uim-fep }
      - { name: uim-mozc }
      # command
      - { name: curl }
      - { name: git }
      - { name: nodejs }
      - { name: tmux }
      - { name: ripgrep }
      - { name: fzf }
        #- { name: rsync }
        #- { name: gawk }
        #- { name: busybox }
        #- { name: bindfs }
      # gui
      - { name: xinit }
      - { name: i3 }
      - { name: rxvt-unicode }
      - { name: x11-xserver-utils }
    tags: apt

  # gui
  - file:
      src: "{{ ansible_facts['user_dir'] }}/dotfiles/{{ item.src }}"
      dest: "{{ ansible_facts['user_dir'] }}/{{ item.dest }}"
      state: link
    loop:
      - { src: '.Xresources', dest: '.Xresources' }
      - { src: '.uim', dest: '.uim' }
      - { src: '.xsessionrc', dest: '.xsessionrc' }
    tags: gui

  # font
  - git:
      repo: https://github.com/yuru7/HackGen.git
      dest: "{{ansible_facts['user_dir']}}/dotfiles/tmp/HackGen"
      depth: 1
      update: no
    tags: font
  - file:
     src: "{{ansible_facts['user_dir']}}/dotfiles/tmp/HackGen/build"
     dest: "{{ansible_facts['user_dir']}}/.fonts"
     state: link
    tags: font

  # vim
  ## vim-plug
  - git:
      repo: https://github.com/junegunn/vim-plug.git
      dest: "{{ansible_facts['user_dir']}}/dotfiles/tmp/vim-plug"
      depth: 1
      update: no
    tags: vim
  - file:
      path: "{{ansible_facts['user_dir']}}/.local/share/nvim/site/autoload/"
      state: directory
    tags: vim
  - file:
     src: "{{ansible_facts['user_dir']}}/dotfiles/tmp/vim-plug/plug.vim"
     dest: "{{ansible_facts['user_dir']}}/.local/share/nvim/site/autoload/plug.vim"
     state: link
    tags: vim
  ## ap_dark8
  - git:
      repo: https://github.com/apribase/ap_dark8.git
      dest: "{{ansible_facts['user_dir']}}/dotfiles/tmp/ap_dark8"
    tags: vim
  - file:
      path: "{{ansible_facts['user_dir']}}/.local/share/nvim/site/colors/"
      state: directory
    tags: vim
  - file:
     src: "{{ansible_facts['user_dir']}}/dotfiles/tmp/ap_dark8/ap_dark8.vim"
     dest: "{{ansible_facts['user_dir']}}/.local/share/nvim/site/colors/ap_dark8.vim"
     state: link
    tags: vim


  # Copy settings
  #- name: Copy keyboard
  #  copy:
  #    src: {{ ansible_facts['env']['HOME'] }}/dotfiles/ansible/files/etc/default/keyboard
  #    dest: /etc/default/keyboard
  #    backup: yes
  #- name: Copy dhcpcd.conf
  #  copy:
  #    src: {{ ansible_facts['env']['HOME'] }}/dotfiles/ansible/files/etc/dhcpcd.conf
  #    dest: /etc/dhcpcd.conf
  #    backup: yes
  #- name: Copy wpa_supplicant.conf (Wi-Fi)
  #  copy:
  #    src: {{ ansible_facts['env']['HOME'] }}/dotfiles/ansible/files/etc/wpa_supplicant/wpa_supplicant.conf
  #    dest: /etc/wpa_supplicant/wpa_supplicant.conf
  #    backup: yes

